---
- name: Delete Reserved IPs
  ansible.builtin.uri:
    url: "{{ digital_ocean_api_base_url }}/reserved_ips/{{ item }}"
    headers:
      Content-Type: 'application/json'
      Authorization: "Bearer {{ digital_ocean_api_token }}"
    body_format: json
    method: DELETE
    follow_redirects: all
    return_content: true
    status_code:
      - 204
    timeout: 120
  delegate_to: localhost
  register: do_reserved_ip_delete_json_response
  no_log: true
  loop: "{{ do_reserved_ips_to_delete }}"
